language: ruby
rvm:
  - 2.6.2
install:
  - bundle install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate 
  - bundle exec rake db:test:prepare
script:
  - bundle exec rspec
